// Auto-generated by Supabase — regenerate with `supabase gen types typescript`
// We keep friendly interface aliases at the bottom for use throughout the app.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.4"
  }
  public: {
    Tables: {
      api_usage_log: {
        Row: {
          company_id: string
          created_at: string | null
          endpoint_type: string
          estimated_cost_usd: number
          id: string
          input_tokens: number
          model_used: string
          output_tokens: number
          quote_id: string | null
          user_id: string
        }
        Insert: {
          company_id: string
          created_at?: string | null
          endpoint_type: string
          estimated_cost_usd: number
          id?: string
          input_tokens: number
          model_used: string
          output_tokens: number
          quote_id?: string | null
          user_id: string
        }
        Update: {
          company_id?: string
          created_at?: string | null
          endpoint_type?: string
          estimated_cost_usd?: number
          id?: string
          input_tokens?: number
          model_used?: string
          output_tokens?: number
          quote_id?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "api_usage_log_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "api_usage_log_quote_id_fkey"
            columns: ["quote_id"]
            isOneToOne: false
            referencedRelation: "quotes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "api_usage_log_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      chat_messages: {
        Row: {
          content: string
          created_at: string | null
          id: string
          model_used: string | null
          quote_id: string
          role: string
          tokens_used: number | null
        }
        Insert: {
          content: string
          created_at?: string | null
          id?: string
          model_used?: string | null
          quote_id: string
          role: string
          tokens_used?: number | null
        }
        Update: {
          content?: string
          created_at?: string | null
          id?: string
          model_used?: string | null
          quote_id?: string
          role?: string
          tokens_used?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "chat_messages_quote_id_fkey"
            columns: ["quote_id"]
            isOneToOne: false
            referencedRelation: "quotes"
            referencedColumns: ["id"]
          },
        ]
      }
      companies: {
        Row: {
          address: string | null
          created_at: string | null
          default_labor_margin: number | null
          default_material_margin: number | null
          default_payment_terms: string | null
          default_quote_validity_days: number | null
          id: string
          license_number: string | null
          logo_url: string | null
          name: string
          phone: string | null
          quote_count_this_period: number | null
          subscription_tier: string | null
          zip_code: string | null
        }
        Insert: {
          address?: string | null
          created_at?: string | null
          default_labor_margin?: number | null
          default_material_margin?: number | null
          default_payment_terms?: string | null
          default_quote_validity_days?: number | null
          id?: string
          license_number?: string | null
          logo_url?: string | null
          name: string
          phone?: string | null
          quote_count_this_period?: number | null
          subscription_tier?: string | null
          zip_code?: string | null
        }
        Update: {
          address?: string | null
          created_at?: string | null
          default_labor_margin?: number | null
          default_material_margin?: number | null
          default_payment_terms?: string | null
          default_quote_validity_days?: number | null
          id?: string
          license_number?: string | null
          logo_url?: string | null
          name?: string
          phone?: string | null
          quote_count_this_period?: number | null
          subscription_tier?: string | null
          zip_code?: string | null
        }
        Relationships: []
      }
      product_catalog: {
        Row: {
          canonical_name: string | null
          company_id: string
          confidence_score: number | null
          created_at: string | null
          id: string
          manually_verified: boolean | null
          normalized_attributes: Json | null
          normalized_category: string | null
          original_name: string
          sku: string | null
          source_file: string | null
          unit: string | null
          unit_price: number
          updated_at: string | null
        }
        Insert: {
          canonical_name?: string | null
          company_id: string
          confidence_score?: number | null
          created_at?: string | null
          id?: string
          manually_verified?: boolean | null
          normalized_attributes?: Json | null
          normalized_category?: string | null
          original_name: string
          sku?: string | null
          source_file?: string | null
          unit?: string | null
          unit_price: number
          updated_at?: string | null
        }
        Update: {
          canonical_name?: string | null
          company_id?: string
          confidence_score?: number | null
          created_at?: string | null
          id?: string
          manually_verified?: boolean | null
          normalized_attributes?: Json | null
          normalized_category?: string | null
          original_name?: string
          sku?: string | null
          source_file?: string | null
          unit?: string | null
          unit_price?: number
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "product_catalog_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
        ]
      }
      quote_line_items: {
        Row: {
          ai_original_description: string | null
          ai_original_quantity: number | null
          ai_original_unit_cost: number | null
          billable_price: number
          category: string | null
          confidence_flag: string | null
          created_at: string | null
          description: string
          id: string
          item_type: string
          margin_percent: number
          price_source: string | null
          quantity: number
          quote_id: string
          sort_order: number
          unit: string | null
          unit_cost: number
          was_added_manually: boolean | null
          was_edited: boolean | null
        }
        Insert: {
          ai_original_description?: string | null
          ai_original_quantity?: number | null
          ai_original_unit_cost?: number | null
          billable_price: number
          category?: string | null
          confidence_flag?: string | null
          created_at?: string | null
          description: string
          id?: string
          item_type: string
          margin_percent: number
          price_source?: string | null
          quantity: number
          quote_id: string
          sort_order: number
          unit?: string | null
          unit_cost: number
          was_added_manually?: boolean | null
          was_edited?: boolean | null
        }
        Update: {
          ai_original_description?: string | null
          ai_original_quantity?: number | null
          ai_original_unit_cost?: number | null
          billable_price?: number
          category?: string | null
          confidence_flag?: string | null
          created_at?: string | null
          description?: string
          id?: string
          item_type?: string
          margin_percent?: number
          price_source?: string | null
          quantity?: number
          quote_id?: string
          sort_order?: number
          unit?: string | null
          unit_cost?: number
          was_added_manually?: boolean | null
          was_edited?: boolean | null
        }
        Relationships: [
          {
            foreignKeyName: "quote_line_items_quote_id_fkey"
            columns: ["quote_id"]
            isOneToOne: false
            referencedRelation: "quotes"
            referencedColumns: ["id"]
          },
        ]
      }
      quotes: {
        Row: {
          ai_model_used: string | null
          client_address: string | null
          client_email: string | null
          client_name: string | null
          company_id: string
          created_at: string | null
          created_by: string
          estimated_api_cost: number | null
          expires_at: string | null
          id: string
          job_site_address: string | null
          labor_margin_default: number | null
          material_margin_default: number | null
          payment_terms: string | null
          quote_number: string
          review_completed_at: string | null
          scope_description: string | null
          status: string | null
          subtotal: number | null
          tax_rate: number | null
          total: number | null
          total_tokens_used: number | null
          updated_at: string | null
          version: number | null
        }
        Insert: {
          ai_model_used?: string | null
          client_address?: string | null
          client_email?: string | null
          client_name?: string | null
          company_id: string
          created_at?: string | null
          created_by: string
          estimated_api_cost?: number | null
          expires_at?: string | null
          id?: string
          job_site_address?: string | null
          labor_margin_default?: number | null
          material_margin_default?: number | null
          payment_terms?: string | null
          quote_number: string
          review_completed_at?: string | null
          scope_description?: string | null
          status?: string | null
          subtotal?: number | null
          tax_rate?: number | null
          total?: number | null
          total_tokens_used?: number | null
          updated_at?: string | null
          version?: number | null
        }
        Update: {
          ai_model_used?: string | null
          client_address?: string | null
          client_email?: string | null
          client_name?: string | null
          company_id?: string
          created_at?: string | null
          created_by?: string
          estimated_api_cost?: number | null
          expires_at?: string | null
          id?: string
          job_site_address?: string | null
          labor_margin_default?: number | null
          material_margin_default?: number | null
          payment_terms?: string | null
          quote_number?: string
          review_completed_at?: string | null
          scope_description?: string | null
          status?: string | null
          subtotal?: number | null
          tax_rate?: number | null
          total?: number | null
          total_tokens_used?: number | null
          updated_at?: string | null
          version?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "quotes_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quotes_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          company_id: string
          created_at: string | null
          email: string
          full_name: string
          id: string
          is_active: boolean | null
          last_login_at: string | null
          role: string
        }
        Insert: {
          company_id: string
          created_at?: string | null
          email: string
          full_name: string
          id: string
          is_active?: boolean | null
          last_login_at?: string | null
          role: string
        }
        Update: {
          company_id?: string
          created_at?: string | null
          email?: string
          full_name?: string
          id?: string
          is_active?: boolean | null
          last_login_at?: string | null
          role?: string
        }
        Relationships: [
          {
            foreignKeyName: "users_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      get_user_company_id: { Args: never; Returns: string }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

// ─── Friendly Type Aliases ────────────────────────────────────────────────────
// Use these throughout the app instead of reaching into Database["public"]["Tables"]

export type Company = Database["public"]["Tables"]["companies"]["Row"];
export type CompanyInsert = Database["public"]["Tables"]["companies"]["Insert"];
export type CompanyUpdate = Database["public"]["Tables"]["companies"]["Update"];

export type User = Database["public"]["Tables"]["users"]["Row"];
export type UserInsert = Database["public"]["Tables"]["users"]["Insert"];
export type UserUpdate = Database["public"]["Tables"]["users"]["Update"];

export type Quote = Database["public"]["Tables"]["quotes"]["Row"];
export type QuoteInsert = Database["public"]["Tables"]["quotes"]["Insert"];
export type QuoteUpdate = Database["public"]["Tables"]["quotes"]["Update"];

export type QuoteLineItem = Database["public"]["Tables"]["quote_line_items"]["Row"];
export type QuoteLineItemInsert = Database["public"]["Tables"]["quote_line_items"]["Insert"];
export type QuoteLineItemUpdate = Database["public"]["Tables"]["quote_line_items"]["Update"];

export type ChatMessage = Database["public"]["Tables"]["chat_messages"]["Row"];
export type ChatMessageInsert = Database["public"]["Tables"]["chat_messages"]["Insert"];

export type ProductCatalogItem = Database["public"]["Tables"]["product_catalog"]["Row"];
export type ProductCatalogItemInsert = Database["public"]["Tables"]["product_catalog"]["Insert"];

export type ApiUsageLog = Database["public"]["Tables"]["api_usage_log"]["Row"];
export type ApiUsageLogInsert = Database["public"]["Tables"]["api_usage_log"]["Insert"];
